server:
  name: "Vapee Community"

messages:
  prefix: "<gray>[<aqua>VapeeCore</aqua>]</gray> "

ranks:
  track: "ranks"

online-rewards:
  enabled: true
  interval-minutes: 60
  coins: 250
  message:
    enabled: true
    format: "<green>You received <gold><coins> Coins</gold> for <yellow><minutes> minutes</yellow> of playtime.</green>"

settings:
  debug: false
