package dev.vapee.core.activity;

public enum ActivityResult {
    SUCCESS,
    INVALID_ACTIVITY_TYPE,
    ACTIVITY_TYPE_NOT_FOUND,
    ACTIVITY_TYPE_ALREADY_REGISTERED,
    ACTIVITY_TYPE_IN_USE,
    VENUE_NOT_FOUND,
    VENUE_ALREADY_REGISTERED,
    VENUE_IN_USE,
    VENUE_UNAVAILABLE,
    INVALID_SESSION,
    SESSION_NOT_FOUND,
    PLAYER_NOT_LOADED,
    PLAYER_OFFLINE,
    PLAYER_ALREADY_IN_ACTIVITY,
    SESSION_NOT_AVAILABLE,
    SESSION_FULL,
    NOT_PARTICIPANT,
    NOT_ENOUGH_PARTICIPANTS,
    INVALID_STATE,
    HOOK_FAILED
}
